/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    enquiries: Enquiry;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  /**
   * Falls back to the page title and the site description.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  layout?:
    | (
        | {
            eyebrow?: string | null;
            titleLine1?: string | null;
            titleLine2?: string | null;
            body?: string | null;
            primaryLabel?: string | null;
            ctaHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            spacesLabel?: string | null;
            /**
             * Chips that swap the background photograph.
             */
            spaces?:
              | {
                  /**
                   * Unique id, e.g. living-rooms
                   */
                  key: string;
                  name: string;
                  /**
                   * e.g. /images/sp-living.jpg
                   */
                  image: string;
                  id?: string | null;
                }[]
              | null;
            statsIntro?: string | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            intro?: string | null;
            featureImage?: string | null;
            statLabel?: string | null;
            statValue?: string | null;
            statBody?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            services?:
              | {
                  /**
                   * e.g. 01
                   */
                  number: string;
                  icon: 'home' | 'globe' | 'sparkles' | 'zap' | 'layers' | 'box';
                  title: string;
                  description: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesGrid';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'portfolio';
          }
        | {
            steps?:
              | {
                  /**
                   * e.g. 01
                   */
                  n: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'process';
          }
        | {
            reasons?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'whyUs';
          }
        | {
            cities?:
              | {
                  name: string;
                  body: string;
                  /**
                   * e.g. On ground
                   */
                  tag: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'locations';
          }
        | {
            /**
             * Background photograph, e.g. /images/jaiswal/jaiswal-07.jpg
             */
            bgImage?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            /**
             * Small pill above the title.
             */
            badge?: string | null;
            title: string;
            subtitle?: string | null;
            /**
             * e.g. /images/jaiswal/jaiswal-15.jpg
             */
            bgImage?: string | null;
            /**
             * Leave the last crumb's link empty — it is the current page.
             */
            breadcrumbs?:
              | {
                  label: string;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            primaryCtaText?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaText?: string | null;
            secondaryCtaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHero';
          }
        | {
            /**
             * Leave empty to use the standard question set.
             */
            items?:
              | {
                  question: string;
                  answer: string;
                  category?: string | null;
                  id?: string | null;
                }[]
              | null;
            askTitle?: string | null;
            askBody?: string | null;
            askLabel?: string | null;
            askHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqSection';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectsSection';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            body?: string | null;
            phone?: string | null;
            email?: string | null;
            /**
             * One line per line break.
             */
            address?: string | null;
            hours?: string | null;
            nextStepsLabel?: string | null;
            nextSteps?:
              | {
                  /**
                   * e.g. 01
                   */
                  step: string;
                  title: string;
                  desc: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactDetails';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            body?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            spacing?: ('normal' | 'loose') | null;
            cardShadow?: ('sm' | 'md') | null;
            showArrow?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promoBanner';
          }
        | {
            /**
             * Leave empty to use the standard service-area list.
             */
            regions?:
              | {
                  name: string;
                  badge: string;
                  subtext: string;
                  desc: string;
                  specialties?:
                    | {
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  highlight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            specialtiesLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'regionsDirectory';
          }
        | {
            content?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'canvas';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL segment, e.g. choosing-a-modular-kitchen
   */
  slug: string;
  /**
   * Shown on the blog index and used as the meta description.
   */
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  author?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  location?: string | null;
  projectType?: string | null;
  message?: string | null;
  /**
   * Which page or component the enquiry came from.
   */
  source?: string | null;
  status?: ('new' | 'contacted' | 'quoted' | 'won' | 'closed') | null;
  /**
   * Internal only — never shown to the client.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              titleLine1?: T;
              titleLine2?: T;
              body?: T;
              primaryLabel?: T;
              ctaHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              spacesLabel?: T;
              spaces?:
                | T
                | {
                    key?: T;
                    name?: T;
                    image?: T;
                    id?: T;
                  };
              statsIntro?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              featureImage?: T;
              statLabel?: T;
              statValue?: T;
              statBody?: T;
              ctaLabel?: T;
              ctaHref?: T;
              services?:
                | T
                | {
                    number?: T;
                    icon?: T;
                    title?: T;
                    description?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        portfolio?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              steps?:
                | T
                | {
                    n?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whyUs?:
          | T
          | {
              reasons?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        locations?:
          | T
          | {
              cities?:
                | T
                | {
                    name?: T;
                    body?: T;
                    tag?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              bgImage?: T;
              id?: T;
              blockName?: T;
            };
        pageHero?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
              bgImage?: T;
              breadcrumbs?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              primaryCtaText?: T;
              primaryCtaHref?: T;
              secondaryCtaText?: T;
              secondaryCtaHref?: T;
              id?: T;
              blockName?: T;
            };
        faqSection?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    category?: T;
                    id?: T;
                  };
              askTitle?: T;
              askBody?: T;
              askLabel?: T;
              askHref?: T;
              id?: T;
              blockName?: T;
            };
        projectsSection?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        contactDetails?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              phone?: T;
              email?: T;
              address?: T;
              hours?: T;
              nextStepsLabel?: T;
              nextSteps?:
                | T
                | {
                    step?: T;
                    title?: T;
                    desc?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        promoBanner?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              ctaLabel?: T;
              ctaHref?: T;
              spacing?: T;
              cardShadow?: T;
              showArrow?: T;
              id?: T;
              blockName?: T;
            };
        regionsDirectory?:
          | T
          | {
              regions?:
                | T
                | {
                    name?: T;
                    badge?: T;
                    subtext?: T;
                    desc?: T;
                    specialties?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    highlight?: T;
                    id?: T;
                  };
              specialtiesLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        canvas?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  publishedAt?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  location?: T;
  projectType?: T;
  message?: T;
  source?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}